version: '3.1'
services:
  econ_sim:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    environment:
      TEST_VAR:  chickensalt
    entrypoint: /bin/bash
    